language:
  - node_js

node_js:
  - "5.1"

before_script:
  - npm install grunt-cli -g
  - npm install

script:
  - grunt test

before_install:
  - pip install --user codecov

after_success:
  - codecov --file test/coverage/lcov.info --disable search
